### ISSUE TITLE
Daily Quest - Hitting a Walleye

### ISSUE THREAD

**Issue by MeatyBoii** [GuabinaCore/WoWKoi#1020]
**Links:** https://www.wowhead.com/quest=26414/hitting-a-walleye#comments

**What is happening:** Currently the quest drops fishes that are attributed to other daily quests: https://www.wowhead.com/item=57245/gigantic-catfish
https://www.wowhead.com/item=58856/royal-monkfish#comments

**What should happen:**
The only item that should drop related to this quest is https://www.wowhead.com/item=58503/hardened-walleye

**Comment by Cefiro-Caecias** [comment]
Fixed. Available in the next update.

**Comment by MeatyBoii** [comment]
I wanted to point out that it was not fixed. Today whilst doing this quest I fished up Royal Monkfish and Gigantic Catfish again, in rather large numbers.
