### ISSUE TITLE
[Tyce] - Spell Monk: Zen Pilgrimage: Return

### ISSUE THREAD

**Issue by Exlyss** [GuabinaCore/WoWKoi#2185]
**Links:**
https://www.wowhead.com/spell=126895/zen-pilgrimage-return

**What is happening:**
When the player leaves the Class Hall with Hearthstone/Portal to Dalaran/Any other mean EXCEPT said spell, the spell remains bugged in Zen Pilgrimage: Return instead of returning as Zen Pilgrimage (as stated in the spell description "Leaving the Wandering Isle will cancel Zen Pilgrimage: Return. As an example if the player leaves the Class Hall and then uses the spell, he will return where he first used the spell to GO to Class Hall.

**What should happen:**
Even if the player leaves the Class Hall without using Zen Pilgrimage: Return, the spell should revert to Zen Pilgrimage.

I'm at Dalaran but the spell still says "Return".
![WoWScrnShot_032921_191812](https://user-images.githubusercontent.com/64436148/112874682-8471b900-90c3-11eb-936b-89b2e7fcddc2.jpg)

**Comment by ShikoSCS** [comment]
Fixed

**Comment by Hagigamer** [comment]
This is still happening to me today, every time I leave class hall without using return.
