### ISSUE TITLE
[Major Issue] Profession Item Levels set to 7.3 values

### ISSUE THREAD

**Issue by djawl** [GuabinaCore/WoWKoi#2998]
Links:
[7.0 Item for reference](https://web.archive.org/web/20161207055640mp_/http://ptr.wowhead.com/spell=194788)
[Tailoring Quest](https://www.wowhead.com/quest=38970/the-queens-grace-loom) - [Tailoring Guide](https://www.wowhead.com/legion-tailoring-guide)
[Leatherworking Quest](https://www.wowhead.com/quest=40214/fel-tanning) - [Leatherworking Guide](https://www.wowhead.com/legion-leatherworking-guide)
[Blacksmithing Quest](https://www.wowhead.com/quest=38533/tribal-knowledge) - [Blacksmithing Guide](https://www.wowhead.com/legion-blacksmithing-guide)
[Jewelcrafting Quest](https://www.wowhead.com/quest=40558/socket-to-me) - [Jewelcrafting Guide](https://www.wowhead.com/legion-jewelcrafting-guide)
[Jewelcrafting Recipe Vendor](https://www.wowhead.com/npc=100500/jabrul) - [Jewelcrafting Guide](https://www.wowhead.com/legion-jewelcrafting-guide)
[Enginering Quest](https://www.wowhead.com/quest=40882/court-of-stars-revamping-the-recoil) - [Engineering Guide](https://www.wowhead.com/legion-engineering-guide)
[Alchemy Quest](https://www.wowhead.com/quest=39341/vault-of-the-wardens-demons-bile) - [Alchemy Guide](https://www.wowhead.com/legion-alchemy-guide)
[Inscription Quest](https://www.wowhead.com/quest=39957/demon-ink) - [Inscription Guide](https://www.wowhead.com/legion-inscription-guide)

**What is happening:**

At the moment all crafted items have their Item Level (IL) values set to 7.3. Meaning that instead of being 815 they are 850.
This results in virtually all content on release and even normal difficulty of the first raid is deemed almost worthless instantly by simply wearing a lot of crafted gear. 

That's only the first problem however. Crafted gear also has the ability to be improved with an item called [Obliterum](https://web.archive.org/web/20180629233045/https://www.wowhead.com/item=124125/obliterum) which, unless restricted, allows you to increase the IL all the way up to 900. This was capped at 850 during 7.0 as can be seen [HERE](https://web.archive.org/web/20160810105704/https://www.wowhead.com/item=124125/obliterum).

So unless these problems are addressed it will completely break the natural gearing progression on launch. 

So there's only really 2 options:

1. Above I have linked to all the Quests/Vendors that teaches the recipes for the **EPIC** Crafted Items, disabling/removing these on launch would make it so people can't get access to the gear which would pretty much break the entire point of progressive legion.

2. Change the values on all the crafted **EPIC** items back to their 7.0 values (which is 815 base) and cap the ability to upgrade them using [Obliterum](https://web.archive.org/web/20180629233045/https://www.wowhead.com/item=124125/obliterum) to 850 Item Level. **ALL THE ITEMS FOR EACH RESPECTIVE PROFESSION CAN BE FOUND IN THE GUIDES I LINKED ABOVE**

**Comment by Cefiro-Caecias** [comment]
Done.

**Comment by Arkanheal** [comment]
@Sefrenia-Caecias This isn't fixed, I still find people with 900 iLVL crafted gear

**Comment by Arkanheal** [comment]
@ShikoSCS FYI

**Comment by ShikoSCS** [comment]
A correction was made to avoid that it could be improved to an itemlvl higher than 850. But items already created with itemlvl 900 are a problem, we will see what we can do to limit them.

Please, check if you can improve the items in more than 850 and confirm us to close the report
