### ISSUE TITLE
[Core] - Paladin - Fist of Justice talent

### ISSUE THREAD

**Issue by alekso999** [GuabinaCore/WoWKoi#951]
**Links:**

from WoWHead or our Armory

**What is happening:**

It doesn't do anything.

**What should happen:**
It should reduce the remaining cooldown on Hammer of Justice by 2.5 sec for each holy power spent.

**Comment by Majeran0** [comment]
Divine Storm refunds cd correctly, Templar's Verdict does not.

**Comment by ShikoSCS** [comment]
Fixed, please test it

**Comment by alekso999** [comment]
Still doesn't work at all. Neither templar's verdict nor divine storm reduce it.

**Comment by Majeran0** [comment]
Can, confirm - its even worse now since Divine Storm stopped affecting reduction.

**Comment by ShikoSCS** [comment]
Excuse me, please try again once the fix is announced in the changelog-------- Mensaje original --------Asunto: Re: [GuabinaCore/WoWKoi] [Core] - Paladin - Fist of Justice talent (#951)De: Racq Para: GuabinaCore/WoWKoi CC: ShikoSCS ,State change 
Still doesn't work at all. Neither templar's verdict nor divine storm reduce it.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GuabinaCore/WoWKoi/issues/951#issuecomment-628757531",
"url": "https://github.com/GuabinaCore/WoWKoi/issues/951#issuecomment-628757531",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ShikoSCS** [comment]
Excuse me, please try again once the fix is announced in the changelog-------- Mensaje original --------Asunto: Re: [GuabinaCore/WoWKoi] [Core] - Paladin - Fist of Justice talent (#951)De: Filip Fidkowski Para: GuabinaCore/WoWKoi CC: ShikoSCS ,State change 
Can, confirm - its even worse now since Divine Storm stopped affecting reduction.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/GuabinaCore/WoWKoi/issues/951#issuecomment-628794375",
"url": "https://github.com/GuabinaCore/WoWKoi/issues/951#issuecomment-628794375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alekso999** [comment]
@ShikoSCS still doesn't work at all.
